name: Lints

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install
    - name: Lint files with Rubocop
      run: |
        bundle exec rubocop
